let items=Array.isArray(window.ITEMS)?window.ITEMS:[];let filter='must',cat='',company='',query='';const $=s=>document.querySelector(s);
function esc(v=''){return String(v).replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]))}
function scoreClass(x){return x.priority==='must'?'must':x.exclusive?'exclusive':x.followUp?'follow':'normal'}
function badge(x){return x.priority==='must'?'오늘 꼭 볼 것':x.exclusive?'단독·속보 후보':x.followUp?'후속 취재 후보':'모니터링'}
function filtered(){let a=items.filter(x=>filter==='all'||(filter==='must'&&x.priority==='must')||(filter==='exclusive'&&x.exclusive)||(filter==='follow'&&x.followUp));if(cat)a=a.filter(x=>x.category===cat);if(company)a=a.filter(x=>(x.companies||[]).includes(company));if(query){const q=query.toLowerCase();a=a.filter(x=>(x.title+' '+x.summary+' '+x.sourceName+' '+x.category+' '+(x.companies||[]).join(' ')+' '+(x.tags||[]).join(' ')).toLowerCase().includes(q))}const sort=$('#sort').value;return a.sort((a,b)=>sort==='score'?b.score-a.score:sort==='coverage'?((b.clusterCount||1)-(a.clusterCount||1))||b.score-a.score:new Date(b.published)-new Date(a.published))}
function render(){const a=filtered();$('#cards').innerHTML=a.length?a.map(x=>`<article class="card ${scoreClass(x)}" onclick="openItem('${esc(x.id)}')"><div class="card-top"><span class="badge ${scoreClass(x)}">${badge(x)}</span><span class="score">${x.score||0}점</span></div><div class="meta">${esc(x.sourceName||'')} · ${esc(x.publishedLabel||x.published||'')} · ${esc(x.category||'')}</div><div class="title">${esc(x.title)}</div><div class="summary"><b class="why">${esc(x.whyNow||'')}</b><br>${esc(x.summary||'')}</div><div class="signal-row"><span class="signal">이슈 ${esc(x.clusterId||'-')}</span><span class="signal">관련 ${x.clusterCount||1}건</span>${x.earliestObservedSource?`<span class="signal">최초관측 ${esc(x.earliestObservedSource)}</span>`:''}</div>${x.keyNumber?`<div class="key-number">${esc(x.keyNumber)}</div>`:''}<div class="bottom">${(x.companies||[]).slice(0,5).map(t=>`<span class="tag">${esc(t)}</span>`).join('')}${(x.tags||[]).slice(0,4).map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</div></article>`).join(''):`<div class="card"><div class="summary">${items.length?'현재 선택 조건에 맞는 기사가 없습니다.':'수집 데이터가 없습니다.'}</div></div>`;$('#resultCount').textContent=`${a.length}건`}
function openItem(id){const x=items.find(i=>String(i.id)===String(id));if(!x)return;const sources=(x.coveredBy||[]).map(s=>`<span class="tag">${esc(s)}</span>`).join('');$('#detail').innerHTML=`<span class="badge ${scoreClass(x)}">${badge(x)}</span><h2>${esc(x.title)}</h2><div class="meta">${esc(x.sourceName||'')} · ${esc(x.publishedLabel||x.published||'')} · ${esc(x.category||'')}</div><div class="scorebox"><div><small>취재가치</small><b>${x.score||0}</b></div><div><small>단독 후보</small><b>${x.exclusiveScore??'-'}</b></div><div><small>후속 가치</small><b>${x.followScore??'-'}</b></div><div><small>이슈 확산</small><b>${x.clusterCount||1}개</b></div></div><div class="quote"><b>왜 지금 봐야 하나</b><br>${esc(x.whyNow||'')}</div><h3>경쟁지·매체 동향</h3><p>현재 이슈를 확인한 매체: ${sources||'아직 1개 매체에서만 확인'}</p><p class="muted">최초 관측 시각: ${esc(x.earliestObservedAt||'-')} · 최초 관측 매체: ${esc(x.earliestObservedSource||'-')}</p><h3>기사 핵심</h3><p>${esc(x.summary||'')}</p><h3>취재 포인트</h3>${list(x.points)}<h3>추가 확인 질문</h3>${list(x.questions)}<h3>관련 기업</h3>${list(x.companies)}<h3>원문</h3><p class="source-line">${esc(x.sourceName||'')} · ${esc(x.url||'')}</p><p><a href="${esc(x.url||'#')}" target="_blank" rel="noopener">원문 기사 열기 ↗</a></p>`;$('#modal').classList.remove('hidden')}
function list(a){return Array.isArray(a)&&a.length?`<ul>${a.map(v=>`<li>${esc(v)}</li>`).join('')}</ul>`:'<p>등록된 항목이 없습니다.</p>'}
function counts(){$('#countAll').textContent=items.length;$('#countMust').textContent=items.filter(x=>x.priority==='must').length;$('#countExclusive').textContent=items.filter(x=>x.exclusive).length;$('#countFollow').textContent=items.filter(x=>x.followUp).length;$('#statTotal').textContent=items.length;$('#statMust').textContent=items.filter(x=>x.priority==='must').length;$('#statExclusive').textContent=items.filter(x=>x.exclusive).length;$('#statCompetition').textContent=items.filter(x=>(x.clusterCount||1)>=2).length}
function setupCompanies(){const c=[...new Set(items.flatMap(x=>x.companies||[]))].filter(Boolean).sort();$('#companyChips').innerHTML=c.slice(0,24).map(v=>`<button class="chip" data-company="${esc(v)}">${esc(v)}</button>`).join('');document.querySelectorAll('[data-company]').forEach(b=>b.onclick=()=>{company=company===b.dataset.company?'':b.dataset.company;render()})}
function bindUI(){document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav').forEach(n=>n.classList.remove('active'));b.classList.add('active');filter=b.dataset.filter;$('#viewTitle').textContent=b.textContent.trim().replace(/\s+\d+$/,'');render()});document.querySelectorAll('.chip[data-cat]').forEach(b=>b.onclick=()=>{cat=cat===b.dataset.cat?'':b.dataset.cat;render()});$('#search').oninput=e=>{query=e.target.value;render()};$('#sort').onchange=render;$('#reset').onclick=()=>{filter='must';cat='';company='';query='';$('#search').value='';document.querySelectorAll('.nav').forEach(n=>n.classList.toggle('active',n.dataset.filter==='must'));render()};$('#close').onclick=()=>$('#modal').classList.add('hidden');$('#modal').onclick=e=>{if(e.target.id==='modal')$('#modal').classList.add('hidden')}}
function showError(message){$('#cards').innerHTML=`<div class="card must"><div class="title">데이터 로딩 오류</div><div class="summary">${esc(message)}</div></div>`;$('#today').textContent='뉴스 데이터 연결을 확인하세요.'}
function init(){try{if(!Array.isArray(window.ITEMS))throw new Error('data.js가 로드되지 않았습니다.');items=window.ITEMS;bindUI();counts();setupCompanies();render();const now=new Date();$('#today').textContent=`${now.getFullYear()}년 ${now.getMonth()+1}월 ${now.getDate()}일 · ${items.length}건 로드 · 30분 주기 자동 수집`;}catch(err){console.error('Auto Desk init failed',err);showError(err?.message||'알 수 없는 오류')}}
init();