import { isPublicInfoLink } from './sources.js';

const SEOUL_PRESS_URL='https://www.seoul.go.kr/news/news_report.do?tr_code=rsite';
const SEOUL_DATA_URL='https://data.seoul.go.kr/';
const DISTRICTS=[['강남구','https://www.gangnam.go.kr/'],['강동구','https://www.gangdong.go.kr/'],['강북구','https://www.gangbuk.go.kr/'],['강서구','https://www.gangseo.seoul.kr/'],['관악구','https://www.gwanak.go.kr/'],['광진구','https://www.gwangjin.go.kr/'],['구로구','https://www.guro.go.kr/'],['금천구','https://www.geumcheon.go.kr/'],['노원구','https://www.nowon.kr/'],['도봉구','https://www.dobong.go.kr/'],['동대문구','https://www.ddm.go.kr/'],['동작구','https://www.dongjak.go.kr/'],['마포구','https://www.mapo.go.kr/'],['서대문구','https://www.sdm.go.kr/'],['서초구','https://www.seocho.go.kr/'],['성동구','https://www.sd.go.kr/'],['성북구','https://www.sb.go.kr/'],['송파구','https://www.songpa.go.kr/'],['양천구','https://www.yangcheon.go.kr/'],['영등포구','https://www.ydp.go.kr/'],['용산구','https://www.yongsan.go.kr/'],['은평구','https://www.ep.go.kr/'],['종로구','https://www.jongno.go.kr/'],['중구','https://www.junggu.seoul.kr/'],['중랑구','https://www.jungnang.go.kr/']];
const FILE_RE=/\.(pdf|hwp|hwpx|xlsx?|csv|docx?|pptx?|zip)(\?|#|$)/i;
const DATA_RE=/(통계|데이터|현황|실적|지표|분석|예산|결산|재정|계약|입찰|보조금|지원금|사업비|고시|공고|행정예고|입법예고|감사|위원회|회의|인허가|사업계획|공모)/;
function clean(s=''){return s.replace(/<[^>]*>/g,' ').replace(/&nbsp;/g,' ').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/\s+/g,' ').trim()}
function category(t=''){if(/통계|데이터|현황|실적|지표|분석/.test(t))return'데이터·통계';if(/예산|결산|재정|계약|입찰|보조금|지원금|사업비/.test(t))return'예산·재정';if(/주택|건축|부동산|도시계획|재개발|재건축|용적률/.test(t))return'부동산';if(/교통|지하철|버스|도로/.test(t))return'교통';if(/복지|출생|청년|어르신|장애|돌봄/.test(t))return'복지';if(/안전|재난|화재|사고|단속|적발/.test(t))return'안전';if(/고시|공고|행정예고|입법예고|감사|위원회|회의/.test(t))return'행정·공고';return'정책·사업'}
function score(t=''){let n=48;for(const [r,p] of [[/최초|유일|단독/,16],[/증가|급증|확대|감소|급감|변경|신규/,9],[/\d+(?:\.\d+)?\s*(?:억|억원|조원|%|명|가구|세대)/,8],[/예산|사업비|계약|수의계약|민간위탁|보조금/,10],[/재개발|재건축|도시계획|용적률|인허가/,9],[/논란|의혹|감사|적발|단속|처분/,12]])if(r.test(t))n+=p;return Math.min(98,n)}
function abs(h,b){try{return new URL(h,b).href}catch{return null}}
function parseLinks(html,base,org,prefix){const out=[],seen=new Set();const re=/<a[^>]+href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi;let m;while((m=re.exec(html))&&out.length<80){const title=clean(m[2]),href=abs(m[1],base);if(!href||title.length<6||/로그인|검색|메뉴|바로가기|사이트맵|개인정보/.test(title)||seen.has(href))continue;seen.add(href);const isFile=FILE_RE.test(href)||FILE_RE.test(title);const isPublic=isPublicInfoLink(title)||DATA_RE.test(title);if(!isPublic&&!isFile)continue;const sc=score(title)+(isPublic?4:0),cat=category(title);out.push({id:`${prefix}-${out.length+1}`,level:sc>=84?'S':sc>=72?'A':'B',category:cat,org,date:new Date().toISOString().slice(0,10),score:Math.min(98,sc),title:isFile?`[첨부파일] ${title}`:title,summary:`${org} 공개정보에서 자동 발견. 본문·첨부파일·관련 데이터와 과거 수치를 비교합니다.`,why:sc>=84?'수치·예산·계약·정책 변화 등 추가 취재 신호가 강합니다.':cat==='데이터·통계'?'데이터·통계 자료로 과거 수치와 비교할 가치가 있습니다.':'공개정보로 확인됐으며 추가 자료 확인이 필요합니다.',keyNumber:(title.match(/\d+(?:\.\d+)?\s*(?:억|억원|조원|%|명|가구|세대)/)||[])[0]||'',tags:['자동수집',org,cat,isFile?'첨부파일':''].filter(Boolean),questions:['원자료와 첨부파일의 세부 수치는?','전년·전월 또는 기존 계획과 무엇이 달라졌나?','예산·계약·인허가·위원회 자료와 연결되는가?','다른 24개 자치구·서울시 전체 추세와 비교하면 특이한가?'],data:'원문·첨부파일·예산서·계약자료·통계·의회자료',attachments:isFile?[href]:[],source:href});}return out}
async function crawl(url,org,prefix){try{const r=await fetch(url,{headers:{'User-Agent':'Seoul-Reporting-Radar/1.0'}});if(!r.ok)throw new Error(String(r.status));return parseLinks(await r.text(),url,org,prefix)}catch(e){return[{id:`${prefix}-error`,level:'follow',category:'수집상태',org,date:new Date().toISOString().slice(0,10),score:0,title:`${org} 수집 경로 확인 필요`,summary:`자동 접근 실패: ${e.message}`,why:'게시판/RSS/API 주소를 개별 보정해야 합니다.',tags:['수집오류',org],questions:['보도자료·데이터·공고 게시판 주소 확인','RSS/API 제공 여부 확인'],data:'수동 엔드포인트 등록 필요',source:url}]}}
async function getRadar(){const batches=await Promise.all([crawl(SEOUL_PRESS_URL,'서울시','seoul-press'),crawl(SEOUL_DATA_URL,'서울시 데이터','seoul-data'),...DISTRICTS.map(([name,url],i)=>crawl(url,name,`district-${i+1}`))]);return batches.flat().sort((a,b)=>b.score-a.score)}
export default{async fetch(request,env){const u=new URL(request.url);if(u.pathname==='/api/radar'){try{return Response.json({ok:true,updatedAt:new Date().toISOString(),items:await getRadar()})}catch(e){return Response.json({ok:false,error:String(e),items:[]},{status:502})}}return env.ASSETS.fetch(request)},async scheduled(event,env,ctx){ctx.waitUntil((async()=>{const items=await getRadar();console.log(JSON.stringify({type:'public-info-radar',count:items.length,updatedAt:new Date().toISOString()}))})())}};
