const SEOUL_PRESS_URL = 'https://www.seoul.go.kr/news/news_report.do?tr_code=rsite';

const DISTRICTS = [
 ['강남구','https://www.gangnam.go.kr/'],['강동구','https://www.gangdong.go.kr/'],['강북구','https://www.gangbuk.go.kr/'],['강서구','https://www.gangseo.seoul.kr/'],['관악구','https://www.gwanak.go.kr/'],
 ['광진구','https://www.gwangjin.go.kr/'],['구로구','https://www.guro.go.kr/'],['금천구','https://www.geumcheon.go.kr/'],['노원구','https://www.nowon.kr/'],['도봉구','https://www.dobong.go.kr/'],
 ['동대문구','https://www.ddm.go.kr/'],['동작구','https://www.dongjak.go.kr/'],['마포구','https://www.mapo.go.kr/'],['서대문구','https://www.sdm.go.kr/'],['서초구','https://www.seocho.go.kr/'],
 ['성동구','https://www.sd.go.kr/'],['성북구','https://www.sb.go.kr/'],['송파구','https://www.songpa.go.kr/'],['양천구','https://www.yangcheon.go.kr/'],['영등포구','https://www.ydp.go.kr/'],
 ['용산구','https://www.yongsan.go.kr/'],['은평구','https://www.ep.go.kr/'],['종로구','https://www.jongno.go.kr/'],['중구','https://www.junggu.seoul.kr/'],['중랑구','https://www.jungnang.go.kr/']
];

function clean(s=''){return s.replace(/<[^>]*>/g,' ').replace(/&nbsp;/g,' ').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/\s+/g,' ').trim()}
function category(title=''){if(/정비|주택|부동산|도시계획|용적률|재개발|재건축|공급|역세권/.test(title))return'부동산';if(/예산|재정|사업비|지원금|소상공인|채용|기업|투자/.test(title))return'예산·재정';if(/교통|지하철|버스|도로|횡단보도|철도/.test(title))return'교통';if(/복지|출생|청년|어르신|장애|돌봄|지원/.test(title))return'복지';if(/안전|폭염|재난|화재|사고|수사/.test(title))return'안전';return'행정'}
function score(title=''){let n=55;for(const [re,p] of [[/전국 최초|최초/,14],[/증가|급증|확대|감소|급감/,8],[/억|조원|억원|가구|세대|명/,7],[/예산|사업비|계약|공모|민간|위탁/,8],[/정비|재개발|재건축|도시계획|용적률/,9],[/논란|의혹|주의|단속|적발|수사/,12]])if(re.test(title))n+=p;return Math.min(98,n)}
function parseLinks(html,base,org,prefix){const out=[];const re=/<a[^>]+href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi;let m;const seen=new Set();while((m=re.exec(html))&&out.length<20){const title=clean(m[2]);if(title.length<8||/로그인|검색|메뉴|바로가기|사이트맵/.test(title))continue;let source;try{source=new URL(m[1],base).href}catch{continue}if(seen.has(source))continue;seen.add(source);const sc=score(title);out.push({id:`${prefix}-${out.length+1}`,level:sc>=82?'S':sc>=72?'A':'B',category:category(title),org,date:new Date().toISOString().slice(0,10),score:sc,title,summary:`${org} 홈페이지에서 자동 발견된 게시물입니다. 원문과 첨부파일을 확인해 취재가치를 판단합니다.`,why:sc>=82?'제목에서 수치·예산·사업변화·논란 등 추가 확인 가치가 높은 신호가 발견됐습니다.':'공식 게시물로 확인됐으며 추가 자료 확인이 필요합니다.',keyNumber:/\d+(?:\.\d+)?\s*(?:억|억원|조원|%|명|가구|세대)/.exec(title)?.[0]||'',tags:['자동수집',org,category(title)],questions:['세부 사업비·대상 규모는?','전년 또는 기존 사업과 무엇이 달라졌나?','관련 계약·공모·심의 자료가 있는가?','첨부파일에 추가 숫자나 조건이 있는가?'],data:'원문·첨부파일·예산서·계약자료·의회자료',source});}return out}
async function crawl(url,org,prefix){try{const r=await fetch(url,{headers:{'User-Agent':'Seoul-Reporting-Radar/1.0'}});if(!r.ok)throw new Error(`${r.status}`);return parseLinks(await r.text(),url,org,prefix)}catch(e){return[{id:`${prefix}-error`,level:'follow',category:'행정',org,date:new Date().toISOString().slice(0,10),score:0,title:`${org} 자동수집 확인 필요`,summary:`홈페이지 자동 접근 실패: ${e.message}`,why:'사이트 구조 확인이 필요합니다.',tags:['수집오류',org],questions:['보도자료 게시판 주소 확인','RSS/API 제공 여부 확인'],data:'수동 설정 필요',source:url}]}}
async function getRadar(){const seoul=await crawl(SEOUL_PRESS_URL,'서울시','seoul');const results=[...seoul];for(let i=0;i<DISTRICTS.length;i++){const [name,url]=DISTRICTS[i];const r=await crawl(url,name,`district-${i+1}`);results.push(...r)}return results}
export default{async fetch(request,env){const url=new URL(request.url);if(url.pathname==='/api/radar'){try{return Response.json({ok:true,updatedAt:new Date().toISOString(),items:await getRadar()})}catch(e){return Response.json({ok:false,error:String(e),items:[]},{status:502})}}return env.ASSETS.fetch(request)},async scheduled(event,env,ctx){ctx.waitUntil((async()=>{try{const items=await getRadar();console.log(JSON.stringify({type:'seoul-district-crawl',count:items.length,updatedAt:new Date().toISOString()}))}catch(e){console.error('crawl failed',e)}})())}};
